language: python
python: "3.6.3"
install:
  - pip install -r requirements.txt --cache-dir $HOME/.cache/pip
  - pip install coverage

# command to run tests
# This is the script that enables travis to run the tests
# There are many ways to do dependeing on how you want travis to run and get you coverage
script: true
  - nosetests --with-coverage --coverage report

 # Another command/method to run tests
script:
  - pytest

# This returns the coverage and let's coveralls know the coverage percent.
# Note that travis will build your system and get the coverage.
# It cannot display, therefore coveralls becomes important to get the coverage
# You can also use after_success
after_script:
  - coveralls

# Using codecov to get coverage
after_success:
  - codecov
